package com.mycelis.user.model.dto;

import com.mycelis.user.constant.Gender;
import com.mycelis.user.constant.Status;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.HashSet;
import java.util.Set;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class UserDto {

    private String firstName;
    private String lastName;
    private String email;
    private String mobileNumber;
    private String password;
    private String encryptedPassword; // set by service after hashing
    private String userId;            // generated by service
    private Gender gender;
    private Status status;
    private Set<String> roles = new HashSet<>();
    private Instant createdAt;
    private Instant updatedAt;
    private Instant lastLoggedIn;
}