

mycelis.seed.super-admin.email=${MYCELIS_ADMIN_EMAIL}
mycelis.seed.super-admin.password=${MYCELIS_ADMIN_PASSWORD}
mycelis.seed.super-admin.first-name=Mayowa
mycelis.seed.super-admin.last-name=Olajide
mycelis.seed.super-admin.mobile=${MYCELIS_ADMIN_MOBILE}

